/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StudentView;

import StudentDAO.Studentdao;
import StudentModel.StudentModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SHYAKA
 */
public class StudentView extends javax.swing.JFrame {

    DefaultTableModel newStudentModel;
    public StudentView() {
        initComponents();
        newStudentModel = new DefaultTableModel();
        studentTable.setModel(newStudentModel);
        newStudentModel.addColumn("regNo");
        newStudentModel.addColumn("firstname");
        newStudentModel.addColumn("lastname");
        newStudentModel.addColumn("dob");
        newStudentModel.addColumn("sem");
        newStudentModel.addColumn("course");
        addDataToTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        semesterComb = new javax.swing.JComboBox<>();
        courseComb = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        dob = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        regno = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        view = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("Date Of Birth");

        jLabel4.setText("Studies Info:");

        jLabel5.setText("Semester ");

        jLabel6.setText("Course");

        semesterComb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "semester1", "semester2", "semester3" }));
        semesterComb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                semesterCombItemStateChanged(evt);
            }
        });

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RegNo", "FirstName", "LastName", "DOB", "SEMESTER", "Course"
            }
        ));
        studentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentTable);

        jLabel7.setText("RegNo");

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Save.setText("SAVE ");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        jButton4.setText("DELETE");

        jButton1.setText("Clear");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lastname)
                                    .addComponent(firstname)
                                    .addComponent(dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(regno, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(semesterComb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(courseComb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(372, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Update)
                        .addGap(53, 53, 53)
                        .addComponent(Save)
                        .addGap(36, 36, 36)
                        .addComponent(view)
                        .addGap(54, 54, 54)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(semesterComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(courseComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update)
                    .addComponent(Save)
                    .addComponent(view)
                    .addComponent(jButton4)
                    .addComponent(jButton1))
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        String code = regno.getText();
        String fname = firstname.getText();
        String sname = lastname.getText();
        Date DOB = dob.getDate();
        String sem = semesterComb.getSelectedItem().toString();
        String crs= courseComb.getSelectedItem().toString();
        
        StudentModel student = new StudentModel(code, fname, sname,DOB,sem , crs);
        Studentdao dao = new Studentdao();
        if(dao.savestudent(student)){
            JOptionPane.showMessageDialog(this, "Student registered successfully");
        }else
        {
        JOptionPane.showMessageDialog(this, "Error to register student?");
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void semesterCombItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_semesterCombItemStateChanged
        // TODO add your handling code here:
        
    String url ="jdbc:postgresql://localhost:5432/studentreg";
    String UserNames="postgres";
    String Password="Auca@123";
    Connection connect =null;
    PreparedStatement ps = null;
    ResultSet rs= null;
    Statement st =null;
       try{
      DriverManager.registerDriver(new org.postgresql.Driver());
      connect = DriverManager.getConnection(url,UserNames,Password);
      String sql = "Select course from semesters where semester='"+semesterComb.getSelectedItem()+"' ";
      st = connect.createStatement();
      rs = st.executeQuery(sql);
      courseComb.removeAllItems();
      while(rs.next()) { // Go to next cursor
      
          courseComb.addItem(rs.getString("course"));
      
      }
      
      }
 
  catch(Exception exs){
      exs.printStackTrace();
  }
        
        
    }//GEN-LAST:event_semesterCombItemStateChanged

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        String code = regno.getText();
        String fname = firstname.getText();
        String sname = lastname.getText();
        Date DOB = dob.getDate();
        String sem = semesterComb.getSelectedItem().toString();
        String crs= courseComb.getSelectedItem().toString();
        
        
        StudentModel students = new StudentModel(code,fname,sname,DOB,sem,crs);
        Studentdao Dao = new Studentdao();
        if(Dao.update(students)){
            JOptionPane.showMessageDialog(this, "Location are created successfully");
            newStudentModel.addRow(new Object[]{
            code,
            fname,
            sname,
            DOB,
            sem,
            crs,
            });
            addDataToTable();
        }else
        {
        JOptionPane.showMessageDialog(this, "Error to create Location??");
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
       String url="jdbc:postgresql://localhost:5432/studentreg";
       String userNames="postgres";
       String password="Auca@123";
       Connection connect =null;
       PreparedStatement ps=null;
       ResultSet rs=null;
       Statement st;
       
       try {
        connect = DriverManager.getConnection(url,userNames,password);
        String sql="SELECT * FROM studentregist";
        ps=connect.prepareStatement(sql);
        rs=ps.executeQuery();
        
        DefaultTableModel DTm = (DefaultTableModel)studentTable.getModel();
        DTm.setRowCount(0);
        Object [] rec = new Object [6];
        
        while (rs.next()){
        rec[0]=rs.getString("regNo");
        rec[1]=rs.getString("firstname");
        rec[2]=rs.getString("lastname");
        rec[3]=rs.getDate("dob");
        rec[4]=rs.getString("sem");
        rec[5]=rs.getString("course");
        newStudentModel.addRow(rec);
        }
       connect.close();
       }catch(Exception ex){
       ex.printStackTrace();
       
       }
       
    }
        private void addDataToTable(){
        Studentdao dao=new Studentdao();
        ArrayList<StudentModel> list=dao.retrieve();
        newStudentModel=(DefaultTableModel)studentTable.getModel();
        newStudentModel.setRowCount(0);
        Object[] row=new Object[6];
        for (int i=0;i<list.size();i++) {
            row[0]=list.get(i).getRegNo();
            row[1]=list.get(i).getFirstname();
            row[2]=list.get(i).getLastname();
            row[3]=list.get(i).getDob();
            row[4]=list.get(i).getSem();
            row[5]=list.get(i).getCourse();
            newStudentModel.addRow(row);
            
        }
    }//GEN-LAST:event_viewActionPerformed

    private void studentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentTableMouseClicked
        // TODO add your handling code here:
           semesterComb.setSelectedItem(null);
                courseComb.setSelectedItem(null);
        try {
            newStudentModel=(DefaultTableModel) studentTable.getModel();
                int selectedRows= studentTable.getSelectedRow();
                regno.setText(newStudentModel.getValueAt( selectedRows, 0).toString());
                firstname.setText(newStudentModel.getValueAt(selectedRows, 1).toString());
                lastname.setText(newStudentModel.getValueAt(selectedRows, 2).toString());
                Date dateInfo;
                dateInfo = new SimpleDateFormat("yyyy-MM-dd").parse((String)newStudentModel.getValueAt(selectedRows,3).toString());
                Date.setDate(dateInfo);
                semesterComb.setSelectedItem(newStudentModel.getValueAt(selectedRows, 4).toString());
                courseComb.setSelectedItem(newStudentModel.getValueAt(selectedRows, 5).toString());
                
                
        } catch (ParseException ex) {
            Logger.getLogger(StudentView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_studentTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save;
    private javax.swing.JButton Update;
    private javax.swing.JComboBox<String> courseComb;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField regno;
    private javax.swing.JComboBox<String> semesterComb;
    private javax.swing.JTable studentTable;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
